services:
  dashboard:
    build: .
    container_name: dashboard
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard-nws.nino-rameau.fr`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: always

networks:
  traefik:
    external: true