services:
  dashboard:
    build: .
    container_name: dashboard
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard-nws.nino-rameau.fr`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.no-index.headers.customresponseheaders.X-Robots-Tag=noindex, nofollow, nosnippet, noarchive"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dashboard.middlewares=no-index"
    restart: always

networks:
  traefik:
    external: true